# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Basarat
tagline:          'Basarat Ali Syed'
description:      '<a href="https://twitter.com/basarat" target="_blank">That TypeScript Guy</a>.'
url:              http://basarat.com
baseurl:          /

author:
  name:           'Basarat Ali Syed'
  url:            https://twitter.com/basarat

# Custom vars
github:           https://github.com/basarat
twitter:           https://twitter.com/basarat
collections:
- sections
